# Generated by Django 6.0 on 2026-01-10 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived'), ('suspended', 'Suspended')], default='draft', max_length=32)),
                ('privacy_status', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('video_list', models.JSONField(blank=True, null=True)),
                ('sponsor', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Survey Collection',
                'verbose_name_plural': 'Survey Collections',
            },
        ),
    ]
