# Generated by Django 6.0 on 2026-01-10 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey_collections', '0001_initial'),
        ('surveys', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycollection',
            name='assessments',
            field=models.ManyToManyField(blank=True, help_text='Assessments included in this collection.', related_name='collections', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveycollection',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveycollection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.category'),
        ),
        migrations.AddField(
            model_name='surveycollection',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveycollection',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
