# Generated by Django 6.0 on 2026-01-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_collections', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveycollection',
            name='author',
        ),
        migrations.RemoveField(
            model_name='surveycollection',
            name='enrolled_users',
        ),
        migrations.RemoveField(
            model_name='surveycollection',
            name='privacy_status',
        ),
        migrations.RemoveField(
            model_name='surveycollection',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='surveycollection',
            name='video_list',
        ),
    ]
