# Generated by Django 6.0 on 2026-03-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_collections', '0010_link_surveys_to_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycollectiontranslation',
            name='seo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
