# Generated by Django 6.0 on 2026-08-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_collections', '0012_surveycollection_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycollectiontranslation',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
