# Generated by Django 6.0 on 2026-09-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_collections', '0013_alter_surveycollectiontranslation_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycollection',
            name='cover_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surveycollection',
            name='thumb_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
