# Generated by Django 6.0 on 2026-03-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_rename_table_add_discount'),
        ('survey_collections', '0011_seo_field'),
        ('surveys', '0033_seo_field'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name='price',
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('collection__isnull', True), ('survey__isnull', False)),
                            models.Q(('collection__isnull', False), ('survey__isnull', True)),
                            _connector='OR',
                        ),
                        name='price_exactly_one_parent',
                    ),
                ),
            ],
        ),
    ]
