# Generated by Django 6.0 on 2026-01-10 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tree_id', models.UUIDField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('path_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'surveys_category',
                'indexes': [models.Index(fields=['tree_id', 'category_id'], name='ix_category_tree_category_id')],
                'constraints': [models.UniqueConstraint(fields=('tree_id', 'category_id'), name='uq_category_tree_category_id')],
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('name', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='taxonomy.category')),
            ],
            options={
                'db_table': 'surveys_categorytranslation',
                'indexes': [models.Index(fields=['category', 'language'], name='ix_cat_tr_cat_lang')],
                'constraints': [models.UniqueConstraint(fields=('category', 'language'), name='uq_category_language')],
            },
        ),
    ]
