# Generated by Django 6.0 on 2026-09-16 13:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_backfill_path_text_and_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredCategoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path_text'], name='ix_category_path_text'),
        ),
        migrations.AddIndex(
            model_name='categorytranslation',
            index=models.Index(fields=['slug'], name='ix_cat_tr_slug'),
        ),
        migrations.AddIndex(
            model_name='deferredcategoryevent',
            index=models.Index(fields=['category_id'], name='ix_deferred_cat_id'),
        ),
    ]
