# Generated by Codex on 2026-04-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_child"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="status",
            field=models.CharField(default="active", max_length=32),
        ),
        migrations.CreateModel(
            name="ChildGuardian",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("user_id", models.CharField(db_index=True, max_length=128)),
                ("status", models.CharField(default="active", max_length=32)),
                ("role", models.CharField(blank=True, max_length=64)),
                ("organization_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardians",
                        to="accounts.child",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="childguardian",
            index=models.Index(fields=["user_id", "child"], name="accounts_ch_user_id_2ae46f_idx"),
        ),
        migrations.AddIndex(
            model_name="childguardian",
            index=models.Index(fields=["user_id", "status"], name="accounts_ch_user_id_97f11b_idx"),
        ),
    ]
