"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^nxt4$0#3gdm)^66&gp1ddrh3+%nf4*9$6w7$8r#-d-@=l+xk4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
ALLOWED_HOSTS.extend(filter(None, os.environ.get('ALLOWED_HOSTS', '').split(',')))

if POD_IP := os.environ.get('POD_IP', False):
    ALLOWED_HOSTS.append(POD_IP)


# Application definition

INSTALLED_APPS = [
    "django_prometheus",
    "django.contrib.auth",
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    "strawberry.django",
    "accounts",
    'surveys',
    "taxonomy",
    "survey_collections",
    "classifications",
    "recommendations",
    "user_surveys",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "pkg_auth.integrations.django.PkgAuthMiddleware",
    'django.middleware.common.CommonMiddleware',
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    normalized_database_url = DATABASE_URL.replace("postgresql+asyncpg://", "postgres://")
    DATABASES = {
        "default": env.db_url_config(normalized_database_url),
    }
    DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.postgresql"
else:
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get("DATABASE_ENGINE", "django_prometheus.db.backends.sqlite3"),
            'NAME': os.environ.get('DATABASE_NAME', BASE_DIR / "db.sqlite3"),
            'USER': os.environ.get('DATABASE_USER', 'default'),
            'PASSWORD': os.environ.get('DATABASE_PASS', 'default'),
            "HOST": os.environ.get("DATABASE_HOST", "localhost"),
            "PORT": os.environ.get("DATABASE_PORT", "5432"),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = "accounts.User"

SERVICE_NAME = (
    os.environ.get("SERVICE_NAME")
    or os.environ.get("APP_NAME")
    or "surveys"
)
KEYCLOAK_REALM = os.environ.get("KEYCLOAK_REALM")
KEYCLOAK_BASE_URL = os.environ.get("KEYCLOAK_BASE_URL")
base = (KEYCLOAK_BASE_URL or "").rstrip("/") if KEYCLOAK_BASE_URL else None
if base and KEYCLOAK_REALM:
    KEYCLOAK_WELL_KNOWN_URL = f"{base}/realms/{KEYCLOAK_REALM}/.well-known/openid-configuration"
else:
    KEYCLOAK_WELL_KNOWN_URL = None

# Compute API client id from service/app name
KEYCLOAK_CLIENT_ID = f"{SERVICE_NAME}-api"

USERS_GRPC_TARGET = os.environ.get("USERS_GRPC_TARGET", "localhost:50051")
STRAWBERRY_DJANGO = {
    "FIELD_DESCRIPTION_FROM_HELP_TEXT": True,
    "TYPE_DESCRIPTION_FROM_MODEL_DOCSTRING": True,
}

NATS_URL = os.environ.get("NATS_URL", "nats://localhost:4222")
MESSAGE_BROKER_SUBJECTS = [
    subject.strip()
    for subject in os.environ.get("MESSAGE_BROKER_SUBJECTS", "").split(",")
    if subject.strip()
]

RECOMMENDABLE_CONSUMER_SUBJECTS = [
    subject.strip()
    for subject in os.environ.get(
        "RECOMMENDABLE_CONSUMER_SUBJECTS",
        "courses.>,videos.>,articles.>",
    ).split(",")
    if subject.strip()
]
JETSTREAM_ENABLED = os.environ.get("JETSTREAM_ENABLED", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
JETSTREAM_STREAM_NAME = os.environ.get("JETSTREAM_STREAM_NAME", "FORMS")
JETSTREAM_STREAM_SUBJECTS = [
    subject.strip()
    for subject in os.environ.get("JETSTREAM_STREAM_SUBJECTS", "forms.>").split(",")
    if subject.strip()
]
OUTBOX_SUBJECT_PREFIX = os.environ.get("OUTBOX_SUBJECT_PREFIX", "forms")

# Structured JSON logging (picked up by Promtail -> Loki -> Grafana)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.json.JsonFormatter",
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
