# Generated by Codex on 2026-04-30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("survey_collections", "0012_surveycollection_organization_id"),
        ("surveys", "0036_alter_usage_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_service", models.CharField(max_length=255)),
                ("source_model", models.CharField(max_length=255)),
                ("source_id", models.CharField(max_length=255)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="survey_collections.surveycollection",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_service", "source_model", "source_id"],
                        name="ix_ext_ref_source",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(collection__isnull=False) | Q(survey__isnull=False),
                        name="external_ref_has_local_target",
                    ),
                    models.UniqueConstraint(
                        fields=["source_service", "source_model", "source_id", "collection", "survey"],
                        name="uq_external_ref_source_target",
                        nulls_distinct=False,
                    ),
                ],
            },
        ),
    ]
