# Generated by Django 6.0 on 2026-01-10 17:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('upper_limit', models.FloatField(default=0, verbose_name='Upper Limit')),
                ('lower_limit', models.FloatField(default=0, verbose_name='Lower Limit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Short Answer'), ('textarea', 'Paragraph'), ('number', 'Number'), ('file', 'File Upload'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('radio', 'Radio MCQ Answer'), ('checkbox', 'Checkbox MCQ Answer'), ('dropdown', 'Dropdown MCQ Answer'), ('radio_grid', 'Radio Grid Answer'), ('checkbox_grid', 'Checkbox Grid Answer')], default='radio', max_length=100)),
                ('with_file', models.BooleanField(default=False)),
                ('is_mcq', models.BooleanField(default=False)),
                ('is_grid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('answer_time', models.DurationField(blank=True, null=True, verbose_name='Answer Time')),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('text', 'Short Answer'), ('textarea', 'Paragraph'), ('number', 'Number'), ('file', 'File Upload'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('radio', 'Radio MCQ Answer'), ('checkbox', 'Checkbox MCQ Answer'), ('dropdown', 'Dropdown MCQ Answer'), ('radio_grid', 'Radio Grid Answer'), ('checkbox_grid', 'Checkbox Grid Answer')], default='radio', max_length=100, null=True)),
                ('cover_asset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['section__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('cover_asset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSchemaOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('image_asset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_row', models.BooleanField(blank=True, default=None, null=True)),
                ('is_column', models.BooleanField(blank=True, default=None, null=True)),
                ('ending_option', models.BooleanField(blank=True, default=None, null=True, verbose_name='Ending Option')),
                ('order', models.IntegerField(default=1)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.answerschema')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.classification')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='answerschema',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_schema', to='surveys.question'),
        ),
        migrations.CreateModel(
            name='RecommendedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_materials', to='surveys.action')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.section'),
        ),
        migrations.AddField(
            model_name='answerschema',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.section'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived'), ('suspended', 'Suspended'), ('canceled', 'Canceled'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('started', 'Started'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_activity_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Short Description')),
                ('language', models.CharField(blank=True, choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('ht', 'Haitian Creole'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en-us', max_length=64, null=True, verbose_name='Language')),
                ('assessment_type', models.CharField(choices=[('survey', 'Survey'), ('questionnaire', 'Questionnaire'), ('curriculum', 'Curriculum'), ('exam', 'Exam'), ('smart_form', 'Smart Form'), ('collection', 'Collection')], default='survey', max_length=255, verbose_name='Assessment Type')),
                ('display_option', models.CharField(choices=[('single_question', 'Single Question'), ('list', 'List'), ('normal_form', 'Normal Form')], default='single_question', max_length=255, verbose_name='Display Option')),
                ('is_timed', models.BooleanField(default=False, verbose_name='Is Timed')),
                ('assignable_to_user', models.BooleanField(default=False, verbose_name='Assignable to User')),
                ('is_evaluable', models.BooleanField(default=False, verbose_name='Is Evaluable')),
                ('evaluation_type', models.CharField(blank=True, choices=[('automatic_evaluation', 'Automatic Evaluation'), ('manual_evaluation', 'Manual Evaluation')], default='automatic_evaluation', max_length=255, null=True, verbose_name='Evaluation Type')),
                ('use_score', models.BooleanField(default=True, verbose_name='Use Score')),
                ('use_classifications', models.BooleanField(default=False, verbose_name='Use Classifications')),
                ('use_recommendations', models.BooleanField(default=False, verbose_name='Use Recommendations')),
                ('use_actions', models.BooleanField(default=False, verbose_name='Use Actions')),
                ('allow_end_based_on_answer_repeat', models.BooleanField(default=False, verbose_name='Allow Ending Based on Repeating Answer')),
                ('answers_count_to_end', models.IntegerField(default=0, verbose_name='Answers Count to End')),
                ('end_based_on_answer_repeat_in_row', models.BooleanField(default=False, verbose_name='End Based on Repeating Answer in Row')),
                ('allow_update_answer_options_scores_based_on_classification', models.BooleanField(default=False, verbose_name='Allow Update Answer Options Scores Based on Classification')),
                ('allow_update_answer_options_text_based_on_classification', models.BooleanField(default=False, verbose_name='Allow Update Answer Options Text Based on Classification')),
                ('create_option_for_each_classification', models.BooleanField(default=False, verbose_name='Create Option for Each Classification')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('sponsor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sponsor')),
                ('price', models.FloatField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='taxonomy.category')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_surveys', to='surveys.status', verbose_name='Status')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='status',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_log', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_recommendations', to='surveys.answerschemaoption')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='classification',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='answerschemaoption',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='answerschema',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='action',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='SurveyMediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('cover', 'Cover'), ('thumbnail', 'Thumbnail'), ('attachment', 'Attachment')], max_length=32)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='surveys.survey')),
            ],
            options={
                'indexes': [models.Index(fields=['survey'], name='ix_survey_media_assets_survey')],
            },
        ),
    ]
