from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=255, null=True, verbose_name="Title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=300, null=True, verbose_name="Short Description"),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("af", "Afrikaans"),
                            ("ar", "Arabic"),
                            ("ar-dz", "Algerian Arabic"),
                            ("ast", "Asturian"),
                            ("az", "Azerbaijani"),
                            ("bg", "Bulgarian"),
                            ("be", "Belarusian"),
                            ("bn", "Bengali"),
                            ("br", "Breton"),
                            ("bs", "Bosnian"),
                            ("ca", "Catalan"),
                            ("ckb", "Central Kurdish (Sorani)"),
                            ("cs", "Czech"),
                            ("cy", "Welsh"),
                            ("da", "Danish"),
                            ("de", "German"),
                            ("dsb", "Lower Sorbian"),
                            ("el", "Greek"),
                            ("en", "English"),
                            ("en-au", "Australian English"),
                            ("en-gb", "British English"),
                            ("en-us", "American English"),
                            ("eo", "Esperanto"),
                            ("es", "Spanish"),
                            ("es-ar", "Argentinian Spanish"),
                            ("es-co", "Colombian Spanish"),
                            ("es-mx", "Mexican Spanish"),
                            ("es-ni", "Nicaraguan Spanish"),
                            ("es-ve", "Venezuelan Spanish"),
                            ("et", "Estonian"),
                            ("eu", "Basque"),
                            ("fa", "Persian"),
                            ("fi", "Finnish"),
                            ("fr", "French"),
                            ("fy", "Frisian"),
                            ("ga", "Irish"),
                            ("gd", "Scottish Gaelic"),
                            ("gl", "Galician"),
                            ("he", "Hebrew"),
                            ("hi", "Hindi"),
                            ("hr", "Croatian"),
                            ("hsb", "Upper Sorbian"),
                            ("hu", "Hungarian"),
                            ("hy", "Armenian"),
                            ("ia", "Interlingua"),
                            ("id", "Indonesian"),
                            ("ig", "Igbo"),
                            ("io", "Ido"),
                            ("is", "Icelandic"),
                            ("it", "Italian"),
                            ("ja", "Japanese"),
                            ("ka", "Georgian"),
                            ("kab", "Kabyle"),
                            ("kk", "Kazakh"),
                            ("km", "Khmer"),
                            ("kn", "Kannada"),
                            ("ko", "Korean"),
                            ("ky", "Kyrgyz"),
                            ("lb", "Luxembourgish"),
                            ("lt", "Lithuanian"),
                            ("lv", "Latvian"),
                            ("mk", "Macedonian"),
                            ("ml", "Malayalam"),
                            ("mn", "Mongolian"),
                            ("mr", "Marathi"),
                            ("ms", "Malay"),
                            ("my", "Burmese"),
                            ("nb", "Norwegian Bokmal"),
                            ("ne", "Nepali"),
                            ("nl", "Dutch"),
                            ("nn", "Norwegian Nynorsk"),
                            ("os", "Ossetic"),
                            ("pa", "Punjabi"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("pt-br", "Brazilian Portuguese"),
                            ("ro", "Romanian"),
                            ("ru", "Russian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("sq", "Albanian"),
                            ("sr", "Serbian"),
                            ("sr-latn", "Serbian Latin"),
                            ("sv", "Swedish"),
                            ("sw", "Swahili"),
                            ("ta", "Tamil"),
                            ("te", "Telugu"),
                            ("tg", "Tajik"),
                            ("th", "Thai"),
                            ("tk", "Turkmen"),
                            ("tr", "Turkish"),
                            ("tt", "Tatar"),
                            ("udm", "Udmurt"),
                            ("ug", "Uyghur"),
                            ("uk", "Ukrainian"),
                            ("ur", "Urdu"),
                            ("uz", "Uzbek"),
                            ("vi", "Vietnamese"),
                            ("zh-hans", "Simplified Chinese"),
                            ("zh-hant", "Traditional Chinese"),
                        ],
                        default="en-us",
                        max_length=64,
                        null=True,
                        verbose_name="Language",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("suspended", "Suspended"),
                        ],
                        default="draft",
                        max_length=64,
                        verbose_name="Status",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("survey", "Survey"),
                            ("questionnaire", "Questionnaire"),
                            ("curriculum", "Curriculum"),
                            ("exam", "Exam"),
                            ("smart_form", "Smart Form"),
                        ],
                        default="survey",
                        max_length=255,
                        verbose_name="Assessment Type",
                    ),
                ),
                (
                    "display_option",
                    models.CharField(
                        choices=[
                            ("single_question", "Single Question"),
                            ("list", "List"),
                            ("normal_form", "Normal Form"),
                        ],
                        default="single_question",
                        max_length=255,
                        verbose_name="Display Option",
                    ),
                ),
                ("is_timed", models.BooleanField(default=False, verbose_name="Is Timed")),
                ("assignable_to_user", models.BooleanField(default=False, verbose_name="Assignable to User")),
                ("is_evaluable", models.BooleanField(default=False, verbose_name="Is Evaluable")),
                (
                    "evaluation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("automatic_evaluation", "Automatic Evaluation"),
                            ("manual_evaluation", "Manual Evaluation"),
                        ],
                        default="automatic_evaluation",
                        max_length=255,
                        null=True,
                        verbose_name="Evaluation Type",
                    ),
                ),
                ("use_score", models.BooleanField(default=True, verbose_name="Use Score")),
                ("use_classifications", models.BooleanField(default=False, verbose_name="Use Classifications")),
                ("use_recommendations", models.BooleanField(default=False, verbose_name="Use Recommendations")),
                ("use_actions", models.BooleanField(default=False, verbose_name="Use Actions")),
                (
                    "allow_end_based_on_answer_repeat",
                    models.BooleanField(default=False, verbose_name="Allow Ending Based on Repeating Answer"),
                ),
                ("answers_count_to_end", models.IntegerField(default=0, verbose_name="Answers Count to End")),
                (
                    "end_based_on_answer_repeat_in_row",
                    models.BooleanField(default=False, verbose_name="End Based on Repeating Answer in Row"),
                ),
                (
                    "allow_update_answer_options_scores_based_on_classification",
                    models.BooleanField(
                        default=False, verbose_name="Allow Update Answer Options Scores Based on Classification"
                    ),
                ),
                (
                    "allow_update_answer_options_text_based_on_classification",
                    models.BooleanField(
                        default=False, verbose_name="Allow Update Answer Options Text Based on Classification"
                    ),
                ),
                (
                    "create_option_for_each_classification",
                    models.BooleanField(default=False, verbose_name="Create Option for Each Classification"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Updated At"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
