# Generated by Django 6.0 on 2026-01-13 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='submit_action',
            field=models.CharField(choices=[('next', 'Next section'), ('jump', 'Jump to target section')], default='next', max_length=90),
        ),
        migrations.AddField(
            model_name='section',
            name='submit_action_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.section'),
        ),
    ]
