# Generated by Django 6.0 on 2026-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_slugify_titles_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='display_option',
            field=models.CharField(choices=[('by_question', 'By Question'), ('by_section', 'By Section'), ('full_form', 'Full Form')], default='by_question', max_length=255, verbose_name='Display Option'),
        ),
    ]
