# Generated by Django 6.0 on 2026-01-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_survey_display_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='assessment_type',
            new_name='survey_type',
        ),
    ]
