# Generated by Django 6.0 on 2026-01-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_append_id_to_survey_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='assignable_to_user',
            new_name='is_for_child',
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('survey', 'Survey'), ('questionnaire', 'Questionnaire'), ('curriculum', 'Curriculum'), ('exam', 'Exam'), ('smart_form', 'Smart Form'), ('collection', 'Collection')], default='survey', max_length=255, verbose_name='Survey Type'),
        ),
    ]
