# Generated by Django 6.0 on 2026-01-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_remove_survey_assignable_to_user_survey_is_for_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='is_for_child',
            field=models.BooleanField(default=False, verbose_name='Is For '),
        ),
    ]
