# Generated by Django 6.0 on 2026-01-20 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('survey', 'Survey'), ('questionnaire', 'Questionnaire'), ('curriculum', 'Curriculum'), ('exam', 'Exam'), ('smart_form', 'Smart Form')], default='survey', max_length=255, verbose_name='Survey Type'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('amount_cents', models.IntegerField()),
                ('compare_at_amount_cents', models.IntegerField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='surveys.survey')),
            ],
        ),
    ]
