# Generated by Django 6.0 on 2026-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_backfill_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='time_limit',
            field=models.DurationField(blank=True, null=True, verbose_name='Time Limit'),
        ),
    ]
