# Generated by Django 6.0 on 2026-03-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_survey_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='lock_answers',
            field=models.BooleanField(default=False, verbose_name='Lock Answers'),
        ),
        migrations.AddField(
            model_name='survey',
            name='randomize_options',
            field=models.BooleanField(default=False, verbose_name='Randomize Options'),
        ),
        migrations.AddField(
            model_name='survey',
            name='randomize_questions',
            field=models.BooleanField(default=False, verbose_name='Randomize Questions'),
        ),
    ]
