# Generated by Django 6.0 on 2026-03-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_survey_lock_answers_survey_randomize_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='enable_anti_cheat',
            field=models.BooleanField(default=False, verbose_name='Enable Anti-Cheat'),
        ),
    ]
