# Generated by Django 6.0 on 2026-03-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_move_classifications_to_own_app'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unimessagingoutbox',
            name='idx_outbox_pending',
        ),
        migrations.DeleteModel(
            name='UnimessagingOutbox',
        ),
    ]
