# Generated by Django 6.0 on 2026-03-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0032_postgres_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytranslation',
            name='seo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
