# Generated by Django 6.0 on 2026-09-24 09:29

from django.db import migrations, models

"""Give `Survey` a stored primary language. `forms:AD-1`.

Adds the column only — 0041 fills it, and until it runs every survey reads as
the `"default"` fallback. Run the two together; a deploy that lands 0040 alone
would send the enrolment snapshot's legacy-column fallback to `"default"` for
every survey in the service.

Nullable with no default on purpose. `Survey.primary_locale` is the only thing
that should read this column, and it is the one place that decides what a null
means.
"""


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0039_normalize_survey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='primary_language',
            field=models.CharField(blank=True, help_text="The language this survey's body text is authored in. Read it through Survey.primary_locale, never directly. It decides which language key the legacy title/description/text columns fall back into when a learner enrols, so changing it on a survey that already has content mislabels that content until every row is re-saved.", max_length=10, null=True, verbose_name='Primary Language'),
        ),
    ]
