# Generated by Django 6.0 on 2026-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0050_option_flow_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='shuffle_scope',
            field=models.CharField(choices=[('all', 'All questions'), ('untouched', 'Only questions no edge touches')], db_default='untouched', default='untouched', max_length=16, verbose_name='Shuffle Scope'),
        ),
    ]
