# Generated by Django 6.0 on 2026-10-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0051_shuffle_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='score_basis',
            field=models.CharField(choices=[('answered', 'Answered questions'), ('reached', 'Reached questions'), ('all', 'All questions')], db_default='reached', default='reached', max_length=16, verbose_name='Score Basis'),
        ),
    ]
