# Generated by Django 6.0 on 2026-01-10 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('child_id', models.CharField(blank=True, max_length=255, null=True)),
                ('count_of_ending_options', models.IntegerField(default=0)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.action')),
                ('last_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('text', 'Short Answer'), ('textarea', 'Paragraph'), ('number', 'Number'), ('file', 'File Upload'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('radio', 'Radio MCQ Answer'), ('checkbox', 'Checkbox MCQ Answer'), ('dropdown', 'Dropdown MCQ Answer'), ('radio_grid', 'Radio Grid Answer'), ('checkbox_grid', 'Checkbox Grid Answer')], default='radio', max_length=50)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.question')),
                ('selected_options', models.ManyToManyField(blank=True, to='surveys.answerschemaoption')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_surveys.userassessment')),
            ],
            options={
                'ordering': ['question__section__order', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='UserAssessmentClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.classification')),
                ('user_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_surveys.userassessment')),
            ],
        ),
        migrations.AddField(
            model_name='userassessment',
            name='classifications',
            field=models.ManyToManyField(through='user_surveys.UserAssessmentClassification', to='surveys.classification'),
        ),
        migrations.CreateModel(
            name='UserAssessmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.recommendation')),
                ('user_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_surveys.userassessment')),
            ],
        ),
        migrations.AddField(
            model_name='userassessment',
            name='recommendations',
            field=models.ManyToManyField(through='user_surveys.UserAssessmentRecommendation', to='surveys.recommendation'),
        ),
    ]
