# Generated by Django 6.0 on 2026-01-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_collections', '0003_remove_surveycollection_author_and_more'),
        ('user_surveys', '0002_rename_userassessment_to_usersurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey_collections.surveycollection'),
        ),
    ]
