# Generated by Django 6.0 on 2026-02-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0005_child_remove_usersurvey_child_id_usersurvey_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='is_paid',
        ),
    ]
