# Generated by Django 6.0 on 2026-03-10 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0006_remove_usersurvey_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question_title',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='survey',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='allow_end_based_on_answer_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='allow_update_answer_options_scores_based_on_classification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='allow_update_answer_options_text_based_on_classification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='answers_count_to_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='category_id_snapshot',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='create_option_for_each_classification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='display_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='end_based_on_answer_repeat_in_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='evaluation_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='is_evaluable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='is_for_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='is_timed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='language',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='origin_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='sponsor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='survey_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='survey_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='survey_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='survey_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='use_actions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='use_classifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='use_recommendations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='use_score',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('upper_limit', models.FloatField(default=0)),
                ('lower_limit', models.FloatField(default=0)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='user_surveys.usersurvey')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_surveys.useraction'),
        ),
        migrations.CreateModel(
            name='UserAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('image_asset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_row', models.BooleanField(blank=True, default=None, null=True)),
                ('is_column', models.BooleanField(blank=True, default=None, null=True)),
                ('ending_option', models.BooleanField(blank=True, default=None, null=True)),
                ('order', models.IntegerField(default=1)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='user_surveys.usersurvey')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='user_surveys.useransweroption'),
        ),
        migrations.CreateModel(
            name='UserAnswerSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('with_file', models.BooleanField(default=False)),
                ('is_mcq', models.BooleanField(default=False)),
                ('is_grid', models.BooleanField(default=False)),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_schemas', to='user_surveys.usersurvey')),
            ],
        ),
        migrations.AddField(
            model_name='useransweroption',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='user_surveys.useranswerschema'),
        ),
        migrations.CreateModel(
            name='UserClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_classifications', to='user_surveys.usersurvey')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='useransweroption',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_surveys.userclassification'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='classifications',
            field=models.ManyToManyField(through='user_surveys.UserSurveyClassification', to='user_surveys.userclassification'),
        ),
        migrations.AlterField(
            model_name='usersurveyclassification',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_surveys.userclassification'),
        ),
        migrations.CreateModel(
            name='UserMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.UUIDField(blank=True, null=True)),
                ('asset_id', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=32)),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='user_surveys.usersurvey')),
            ],
        ),
        migrations.CreateModel(
            name='UserPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount_cents', models.IntegerField()),
                ('compare_at_amount_cents', models.IntegerField(blank=True, null=True)),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='user_surveys.usersurvey')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('answer_time', models.DurationField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_asset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='user_surveys.usersurvey')),
            ],
            options={
                'ordering': ['section__order', 'order'],
            },
        ),
        migrations.AddField(
            model_name='useranswerschema',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_schema', to='user_surveys.userquestion'),
        ),
        migrations.AddField(
            model_name='useransweroption',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_surveys.userquestion'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_surveys.userquestion'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='last_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_surveys.userquestion'),
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_recommendations', to='user_surveys.useransweroption')),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_recommendations', to='user_surveys.usersurvey')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='recommendations',
            field=models.ManyToManyField(through='user_surveys.UserSurveyRecommendation', to='user_surveys.userrecommendation'),
        ),
        migrations.AlterField(
            model_name='usersurveyrecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_surveys.userrecommendation'),
        ),
        migrations.CreateModel(
            name='UserSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('cover_asset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('submit_action', models.CharField(blank=True, max_length=90, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('submit_action_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_surveys.usersection')),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='user_surveys.usersurvey')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='userquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='user_surveys.usersection'),
        ),
        migrations.AddField(
            model_name='useranswerschema',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_surveys.usersection'),
        ),
        migrations.AddField(
            model_name='useransweroption',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_surveys.usersection'),
        ),
    ]
