# Generated by Django 6.0 on 2026-03-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0007_remove_useranswer_question_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='language',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='title',
        ),
    ]
