# Generated by Django 6.0 on 2026-03-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0008_remove_usersurvey_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='allow_update_answer_options_scores_based_on_classification',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='allow_update_answer_options_text_based_on_classification',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='create_option_for_each_classification',
        ),
    ]
