# Generated by Django 6.0 on 2026-03-10 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_child'),
        ('user_surveys', '0009_remove_usersurvey_allow_update_answer_options_scores_based_on_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.child'),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
