# Generated by Django 6.0 on 2026-03-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0010_alter_usersurvey_child_delete_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='survey_price',
        ),
        migrations.DeleteModel(
            name='UserPrice',
        ),
    ]
