# Generated by Django 6.0 on 2026-03-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0011_remove_usersurvey_survey_price_delete_userprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='cover_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='thumb_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserMediaAsset',
        ),
    ]
