# Generated by Django 6.0 on 2026-03-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0012_usersurvey_cover_id_usersurvey_thumb_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='origin_id',
        ),
    ]
