# Generated by Django 6.0 on 2026-03-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0013_remove_usersurvey_origin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='title',
        ),
        migrations.RemoveField(
            model_name='useransweroption',
            name='text',
        ),
        migrations.RemoveField(
            model_name='userclassification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usersection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usersection',
            name='title',
        ),
    ]
