# Generated by Django 6.0 on 2026-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0014_remove_useraction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='time_limit',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
