# Generated by Django 6.0 on 2026-03-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0015_usersurvey_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
