# Generated by Django 6.0 on 2026-03-11 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0016_usersurvey_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='lock_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='randomize_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='session_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TabSwitchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_switch_events', to='user_surveys.usersurvey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
