# Generated by Django 6.0 on 2026-03-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0017_useranswer_answered_at_useranswer_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='enable_anti_cheat',
            field=models.BooleanField(default=False),
        ),
    ]
