# Generated by Django 6.0 on 2026-03-12 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0018_usersurvey_enable_anti_cheat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('user_survey', 'question'), name='uq_user_answer_survey_question'),
        ),
    ]
