# Generated by Django 6.0 on 2026-03-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0019_unique_answer_per_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Completed by user'), ('time_expired', 'Time expired'), ('ending_option', 'Ending option threshold reached')], max_length=20, null=True),
        ),
    ]
