# Generated by Django 6.0 on 2026-09-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_recommendable_replace_generic_fk'),
        ('user_surveys', '0021_rename_survey_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('source_service', models.CharField(blank=True, default='', max_length=255)),
                ('source_model', models.CharField(blank=True, default='', max_length=255)),
                ('source_id', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('recommendable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_materials', to='recommendations.recommendable')),
                ('user_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='user_surveys.useraction')),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='user_surveys.usersurvey')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
