# Generated by Django 6.0 on 2026-10-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0023_backfill_user_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='useransweroption',
            name='flow_action',
            field=models.CharField(choices=[('fall_through', 'Fall through'), ('go_to', 'Go to'), ('terminate', 'Terminate')], db_default='fall_through', default='fall_through', max_length=16),
        ),
        migrations.AddField(
            model_name='useransweroption',
            name='flow_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_edges', to='user_surveys.userquestion'),
        ),
    ]
