# Generated by Django 6.0 on 2026-10-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0025_shuffle_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='on_path',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Completed by user'), ('time_expired', 'Time expired'), ('ending_option', 'Ending option threshold reached'), ('routing_terminate', 'Answered option ends the attempt')], max_length=20, null=True),
        ),
    ]
