# Generated by Django 6.0 on 2026-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_surveys', '0028_apply_on_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='score_basis',
            field=models.CharField(choices=[('answered', 'Answered questions'), ('reached', 'Reached questions'), ('all', 'All questions')], db_default='reached', default='reached', max_length=16),
        ),
    ]
